name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno task lint

      - name: Run tests
        run: deno test --coverage=coverage

      - name: Generate coverage report
        run: deno coverage coverage --lcov > coverage.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.lcov
          fail_ci_if_error: false

      - name: Type check
        run: deno check typelang/**/*.ts server/**/*.ts app/**/*.ts
